input {
  http {
    host => "0.0.0.0"
    port => 9504
    codec => json
    user => "logstash_system"
    password => "${LOGSTASH_PASSWORD}"
  }
}

filter {

  geoip {
    source => "client_ip"
    target => "geoip"
    add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}", "%{[geoip][latitude]}" ]
  }

  date {
    match => [ "timestamp", "ISO8601" ]
    target => "@timestamp"
  }

  if [status] == "404" {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => "${ELASTIC_HOSTS}"
    user => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
    ssl => true
    ssl_certificate_verification => true
    cacert => "/usr/share/logstash/certs/ca/ca.crt"
    index => "logstash-%{+YYYY.MM.dd}"
  }

  file {
    path => "/var/log/logstash/output.log"
    codec => json_lines
    flush_interval => 5
  }

  dead_letter_queue {
    path => "/var/lib/logstash/dead_letter_queue"
    enable_dead_letter_queue => true
  }
}
