---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ http://elasticsearch:9200 ]

monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

## X-Pack security credentials
#
elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}


xpack.encryptedSavedObjects.encryptionKey: 2b9cf224058a8bb09eb156160e172d24
xpack.reporting.encryptionKey: 81fc0be1d43fbbe6259f3fe4f380a812
xpack.security.encryptionKey: c1a2dbc6772392069f05d819ac120b12